### ISSUE TITLE
Questions about the source data

### ISSUE THREAD

**Issue by TedShawn** [kirsy05/Antarctic-Snow-Depth-Evaluation-ICESat2-CryoSat2#1]
can I get Kako20 snow depth and snow depth derived from snow buoys data?
by the code you submit, I want to be familiar with the process of the antarctic snow depth evaluation.

**Comment by kirsten-schulze** [comment]
The KaKo20 product is not yet publicly available. However, Snow Buoy data can be downloaded from [this link](https://data.meereisportal.de/relaunch/buoymosaic?lang=de).
